# Generated by Django 3.2 on 2021-05-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210505_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='carsOwned',
        ),
    ]
