# Generated by Django 3.2 on 2021-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_carpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='userName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
