# Generated by Django 3.2 on 2021-05-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_carpost_username'),
        ('main_app', '0006_auto_20210501_1727'),
    ]

    operations = [
    ]
