# Generated by Django 3.2 on 2021-05-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_0005_carpost_username_0006_auto_20210501_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='userName',
        ),
    ]
