# Generated by Django 3.2 on 2021-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('favoriteCar', models.CharField(max_length=50)),
                ('carsOwned', models.CharField(max_length=50)),
                ('carsOwn', models.CharField(max_length=250)),
            ],
        ),
    ]
