# Generated by Django 3.2 on 2021-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210504_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='carsOwned',
            field=models.CharField(max_length=250),
        ),
    ]
